backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: 'static/images' # Media files will be stored in the repo under public/images
public_folder: '/images' # The src attribute for uploaded media will begin with /images

collections:
  - name: 'projects'
    label: 'Projects' # Used in the UI
    folder: 'static/projects' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Main Image', name: 'main_image', widget: 'image' }
      - { label: 'Client', name: 'client', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'posts'
    label: 'Posts' # Used in the UI
    folder: 'static/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Date', name: 'date', widget: 'datetime', date_format: 'DD.MM.YYYY' }
      - { label: 'Main Image', name: 'main_image', widget: 'image' }
      - label: 'Keywords'
        name: 'keyword'
        widget: 'list'
        summary: '{{fields.keyword}}'
        field: { label: 'Keyword', name: 'keyword', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
