backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: 'static/images' # Media files will be stored in the repo under static/images
public_folder: '/images' # The src attribute for uploaded media will begin with /images

collections:
  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projects' # Used in the UI
    folder: 'content' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'image', widget: 'image' }
      - { label: 'Alternative Text', name: 'imageAlt', widget: 'string' }
      - { label: 'Client', name: 'client', widget: 'string' }
      - { label: 'Role', name: 'role', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
