backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
media_folder: static/images # Media files will be stored in the repo under static/images/uploads
public_folder: /images # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "static/projects" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Role", name: "role", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "static/posts" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY" }
      - { label: "Image", name: "image", widget: "image" }
      - label: "Keywords" 
        name: "keywords" 
        widget: "list" 
        field: {label: "Keyword", name: "keyword", widget: "string"}
      - { label: "Content", name: "body", widget: "markdown" }